[phases.build]
cmds = ["npm run build"]
cacheDirectories = []

[start]
cmd = "npx serve -s dist -l 3000"

[staticAssets]
Caddyfile = '''
:{$PORT:3000} {
    root * dist
    encode gzip
    file_server
    try_files {path} {path}/ /index.html
}
'''
